name: Full CI/CD with Security Checks

on:
  pull_request:
    branches:
      - main
      - QA
      - Develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test

  CodeQL:
    name: Run CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'javascript'
      - name: Run CodeQL
        uses: github/codeql-action/analyze@v1

  Snyk:
    name: Run Snyk to check for vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high --org=fabos180 --prune-repeated-subdependencies
        continue-on-error: true

  build-and-deploy:
    needs: [test, CodeQL, Snyk]
    if: github.base_ref == 'refs/heads/QA'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "start login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "fin login"

      # Build and push Docker image for the 'QA' branch
      - name: Build Docker Image
        run: |
          docker build -t fabos180/diplomado_project:0.0.1 .
          docker build -t fabos180/diplomado_project:latest .

      - name: Push Docker Image
        run: |
          docker push fabos180/diplomado_project:0.0.1

      - name: Push Docker Image as latest
        run: |
          docker push fabos180/diplomado_project:latest

      # Setup SSH and deploy Docker image to DigitalOcean for the 'QA' branch
      - name: Install ssh user and pasw
        run: sudo apt-get install -y sshpass

      - name: Ejecutar acción
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD_QA }} ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SSH_USER_QA }}@${{ secrets.SSH_IP_QA }} 'cd web && docker compose down -v && docker compose pull && docker compose up -d --build'
